CREATE TABLE admin_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role TEXT CHECK (role IN ('SUPER_ADMIN', 'MODERATOR')) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);